import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

i18n.use(initReactI18next).init({
    resources: {
        en: {
            translation: {
                "login_title": "Sign in to BII Orbit",
                "remember_me": "Remember me",
                "forgot_password": "Forgot password?",
                "login": "Login",
                "email_placeholder": "name@address.com",
                "login_description": "Sign in to your account to continue.",
                "enter_password": "Enter your password",
                "reset": "Reset password",
                "reset_description": "Lost your password? Enter your email!",
                "reset_password": "Reset password",
                "reset_password_description": "Provide your password & confirm it before proceeding",
                "our_office": "Our office",
                "follow_us": "Follow us",
                "logo_alt": "Logo of BioInnovation Institute",
                "address_bii": "Ole Maaløes Vej 3",
                "postal_bii": "2200, København, Denmark",
                "my_bii_program": "My BII program",
                "network": "Network",
                "resources": "Resources",
                "facility": "Facility",
                "investor_network": "Investor network",
                "investor_network_url": "https://v2.bii-intranet.dk",
                "home": "Home",
                "my_profile": "My profile",
                "logout": "Logout",
                "bioinnovation_institute": "BioInnovation Institute",
                "view_all": "View all",
                "upcoming_events": "Upcoming events",
                "title": "BII investor network",
                "copyright": "all rights reserved",
                "help_center": "Help center",
                "new_features": "Stay updated about new features and releases",
                "follow": "Follow us",
                "back_home": "Back home",
                "news_overview": "News overview",
                "stay_updated": "Stay updated",
                "filters": "Filters",
                "refresh_filter": "Refresh filter",
                "paginated": "Showing {{to}} results from total {{total}}",
                "x_documents": "{{count}} document(s)",
                "keyword": "Enter a keyword...",
                "portfolio_no_results": "Unfortunately, we have not found any results...",
                "reset_filters": "Reset filters",
                "search_input": "search",
                "unavailable_events": "BII currently don't have any events coming up. Click on the button down below to see the events.",
                "companies": "Companies",
                "people": "People",
                "avatar_of": "image of {{name}}",
                "bii_companies": "Companies",
                "resident_companies": "Resident companies",
                "programs": "Programs",
                "collaborators": "Collaborators",
                "target_area": "Target area",
                "service_domains": "Service domains",
                "collaborator_focus": "Collaborator focus",
                "latest_added_collaborator": "Latest added collaborator",
                "geographical_relevance": "Geographical relevance",
                "pinned": "Pinned",
                "bii_recommended": "BII recommended",
                "new": "New",
                "team": "Team",
                "back_to_overview": "Back to overview",
                "reach_out": "Reach out",
                "bii_program": "BII program",
                "bii_anchors": "BII anchors",
                "no_anchor_selected": "No anchor selected.",
                "no_cohort_selected": "No cohort selected.",
                "no_area_selected": "No area selected.",
                "area": "Area",
                "links": "Links",
                "events_user_is_attending": "Events {{name}} is attending",
                "events_employees_are_attending": "Events employees are attending",
                "unavailable_events_company": "{{company}} currently does not have any events coming up. Click on the button down below to see all upcoming events.",
                "unavailable_events_user": "{{user}} currently does not have any events coming up. Click on the button down below to see all upcoming events.",
                "reach_out_to": "Reach out to {{name}}",
                "my_recommendations": "My recommendation and tips and tricks",
                "leave_endorsement": "Leave endorsement",
                "bii_offer": "BII offer",
                "service_description": "Service description",
                "empty_text": "The {{name}} has not been set.",
                "target_vertical": "Target verticals",
                "geographical_focus": "Geographical focus",
                "references": "References",
                "bii_areas": "BII areas",
                "bii_program_and_cohort": "BII program and cohort",
                "latest_added_companies": "BII program and companies",
                "is_on_site_at_bii": "On-site at BII",
                "geographical_interests": "Geographical relevance",
                "search_for_country": "Search for country...",
                "latest_people_joined": "Latest people joined",
                "advisors": "Advisors",
                "community": "Community",
                "fundraising_experience": "Fundraising experience",
                "bii_alumni": "BII alumni",
                "interested_in": "Interested in",
                "expertise": "Expertise",
                "advisor_network_profile": "Advisor network profile",
                "experience": "Experience",
                "background": "Background",
                "motivation": "Motivation",
                "board_network": "Board network",
                "advisor_network": "Advisor network",
                "impact": "Impact",
                "investor_platform": "Investor platform",
                "board_network_profile": "Board network profile",
                "subjects": "Subjects",
                "default_selected_facility_option": "Laboratory",
                "guidelines_before_engaging": "Guidelines before engaging",
                "perform_your_own_due_diligence": "Perform your own due diligence to ensure the credibility and reliability of the individuals or organizations you are working with",
                "continue_accept_guidelines": "By continuing, you agree that you understand and accept these guidelines.",
                "acknowledge_bii_is_not_liable": "Acknowledge that BII is not liable for any outcomes, agreements, or disputes that may arise from these external engagements.",
                "guidelines_block_1": "Please note that the individuals or organizations you are engaging with are external to BioInnovation Institute (BII). While we strive to connect you with valuable resources and experts, BII does not endorse, manage, or take responsibility for the actions, advice, or services provided by these third parties.",
                "guidelines_block_2": "Before proceeding with any engagements, we recommend that you:",
                "guidelines_block_3": "By continuing, you agree that you understand and accept these guidelines.",
                "download": "Download",
                "leave_endorsement_company": "Leave endorsement for {{name}}",
                "endorsement_notification": "Your endorsement will be reviewed and approved before it is shown on the collaborator page.",
                "add_endorsement": "Add endorsement",
                "endorsement_message": "Endorsement message",
                "endorsement_description": "Your name and endorsement message will be displayed.",
                "user_role": "{{role}} at {{company}}"
            }
        },
    },
    lng: "en",
    fallbackLng: "en",
    interpolation: {
        escapeValue: false
    }
});

export default i18n;
